version: "3.9"

services:
  file-ud-fe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5102:80"
    restart: always
    mem_limit: 512m
    cpus: 0.5
    environment:
      - NODE_ENV=production
